/// Nomi eseguibili (lowercase) i cui handle su redm.exe sono leciti.
pub const OWNER_ALLOWLIST: &[&str] = &[
    "explorer.exe",
    "steam.exe",
    "steamwebhelper.exe",
    "steamservice.exe",
    "discord.exe",
    "lenovo.modern.imcontroller.exe",
    "gameinputredistservice.exe",
    "lenovovantageservice.exe",
    "fnplicensingservice64.exe",
    "oplus_remote_service.exe",
    "steamerrorreporter64.exe",
    "hasplms.exe",
    // Processi di sistema protetti (PPL/VSM): espongono il nome ma NON il path a
    // un processo a integrità normale, quindi il filtro su System32 non li prende
    // → allowlist per nome.
    "smss.exe",
    "lsaiso.exe",
    "csrss.exe",
    "lsass.exe",
    "services.exe",
    "svchost.exe",
    "wininit.exe",
    "winlogon.exe",
    "dwm.exe",
    "taskmgr.exe",
    "msmpeng.exe",
    "searchindexer.exe",
    "nvcontainer.exe",
    "nvsphelper64.exe",
    "nvidia web helper.exe",
    "system",
    "registry",
];
